# Generated by Django 4.1.2 on 2022-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
