# Generated by Django 4.1.2 on 2022-10-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
    ]
